### ISSUE TITLE
[FEA] Inference serving with Kubeflow/KServe + Triton-FIL

### ISSUE THREAD

**Issue by hcho3** [rapidsai/cloud-ml-examples#240]
[KServe](https://www.kubeflow.org/docs/external-add-ons/kserve/) is an inference platform that's installed as part of Kubeflow.

**Comment by hcho3** [comment]
1. Upload an example demo model to the Google Cloud storage. For this example, I am using `gs://phcho-kserve-triton-fil-example`. Make sure to lay out the model files like this:
```
models/
* xgboost-agaricus/
* * config.pbtxt
* * 1/
* * * xgboost.model
```
The content of `config.pbtxt` is as follows:
```
backend: "fil"
max_batch_size: 32768
input [
  {
    name: "input__0"
    data_type: TYPE_FP32
    dims: [ 126 ]
  }
]
output [
 {
    name: "output__0"
    data_type: TYPE_FP32
    dims: [ 1 ]
  }
]
instance_group [{ kind: KIND_AUTO }]
parameters [
  {
    key: "model_type"
    value: { string_value: "xgboost" }
  },
  {
    key: "output_class"
    value: { string_value: "true" }
  },
  {
    key: "threshold"
    value: { string_value: "0.5" }
  }
]

dynamic_batching {}
```
2. Install Kubeflow on your K8s cluster.
3. Connect to Kubeflow via istio port-forwarding: `kubectl port-forward svc/istio-ingressgateway -n istio-system 8080:80`
4. Navigate to the "Models" section on the left navbar and then click on the button "+ New Model Server"
5. Paste in the following service YAML:
```
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: xgboost-agaricus
spec:
  predictor:
    triton:
      storageUri: gs://phcho-kserve-triton-fil-example/models
      runtimeVersion: 22.12-py3
      env:
      - name: OMP_NUM_THREADS
        value: "1"
```
